### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by MarcHagen** [lunar-consultancy/jira-wallboard#1]
Could you update this project?
Code is not compiling with maven

Update:
Console log >> https://pastebin.com/HJEF7SSR

**Comment by lunar-consultancy** [comment]
@TakeMeNL: Please compile with a non-root user:

`[INFO] Running 'bower install' in /root/jira-wallboard/frontend`
`[ERROR] bower ESUDO         Cannot be run with sudo`

**Comment by MarcHagen** [comment]
Oke did that but still getting errors
Running in docker installed with 
git, wget, java jdk 8u92 build 14, maven 3.3.9, ant 1.9.7

Console >> https://pastebin.com/17xQTWB2

**Comment by lunar-consultancy** [comment]
@TakeMeNL: Looks like bzip2 is not available in the docker container. (tar (child): bzip2: Cannot exec: No such file or directory)
